---
- hosts: all
  any_errors_fatal: true
  become: true

  tasks:
    - name: APT - Add elastic.co key
      apt_key: url="https://artifacts.elastic.co/GPG-KEY-elasticsearch"
      when: ansible_distribution == "Ubuntu"
      tags: apt

    - name: APT - Add elastic.co repository
      apt_repository: repo="deb https://artifacts.elastic.co/packages/7.x/apt stable main" filename="elastic-7.x" update_cache=yes
      when: ansible_distribution == "Ubuntu"
      tags: apt

    - name: FILEBEAT - Install Filebeat
      apt: pkg=filebeat
      when: ansible_distribution == "Ubuntu"
      tags: apt

#below task needs to be added so that filebeat doesn't hit open files limits.
    - pam_limits:
        domain: filebeat
        limit_type: hard
        limit_item: nofile
        value: 64000
